name: Deployment pipeline

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install dependences
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test

